# Generated by Django 4.2.4 on 2023-08-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apppedidosnow", "0003_produto_gramas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="isbn",
        ),
        migrations.AddField(
            model_name="produto",
            name="código",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
