# Generated by Django 4.2.4 on 2023-08-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apppedidosnow", "0004_remove_produto_isbn_produto_código"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="código",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
