# Generated by Django 4.2.4 on 2023-10-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apppedidosnow", "0006_pedido_remove_produto_código_produto_isbn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="cliente",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="mesa",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
